accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/', views.follow, name='follow'),

]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    # ===================== 댓글 =======================
    path('movies/<int:pk>/comments/', views.comments_create, name='comments_create'),  # 단일 댓글 데이터 저장
    path('movies/<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),  # 단일 댓글 데이터 삭제
    path('movies/<int:movie_pk>/likes/', views.likes, name='likes'),  # 단일 영화 데이터 좋아요 및 좋아요 취소
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    
]

movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')

    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, 
                            null=True, related_name='replies')
    def __str__(self):
        return self.content

movies/forms.py
from django import forms
from .models import Movie, Comment

# 1) Moive
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'description', )

# 2) Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('movie', 'user', 'parent',)

movies/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
from django.views.decorators.http import require_http_methods


@require_http_methods(['GET'])
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)

@require_http_methods(['GET', 'POST'])
@login_required()
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)

@require_http_methods(['GET'])
@login_required()
def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {
        'movie': movie,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'movies/detail.html', context)

@require_http_methods(['POST'])
@login_required()
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.user == movie.user:
        movie.delete()
    return redirect('movies:index')

@require_http_methods(['GET','POST'])
@login_required()
def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.user != movie.user:
        return render(request, 'movies/index.html')
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/update.html', context)

# ===== 댓글 ======
# 1) 댓글 작성
@require_http_methods(['POST'])
@login_required()
def comments_create(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    parent_pk = request.POST.get('parent_pk')
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        if parent_pk:
            comment.parent = Comment.objects.get(pk=parent_pk)
        comment.movie = movie
        # 댓글 작성시 작성자 정보가 함께 저장
        comment.user = request.user
        comment.save()
    return redirect('movies:detail', movie.pk)

# 2) 댓글 삭제
@require_http_methods(['POST'])
@login_required()
def comments_delete(request, movie_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user: 
        comment.delete()
    return redirect('movies:detail', movie_pk)

# 3) like
@require_http_methods(['POST'])
@login_required()
def likes(request, movie_pk):
    if request.user.is_authenticated: 
        movie = Movie.objects.get(pk=movie_pk)
        
        if movie.like_users.filter(pk=request.user.pk).exists():
            movie.like_users.remove(request.user)  

        else:
            movie.like_users.add(request.user) 
        return redirect('movies:index') 
    
    return redirect('movies:login')  

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <hr>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:index' %}">BACK</a>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <hr>
  <div>
    <h5>{{ movie.title }}</h5>
    {% if request.user == movie.user %}
      <p>{{ movie.description }}</p>
    {% else %}
      <p>다른 유저가 작성한 글</p>
    {% endif %}
  </div>
  <a href="{% url 'movies:update' movie.pk %}">UPDATE</a>
  <form action="{% url 'movies:delete' movie.pk %}" method='POST'>
    {% csrf_token %}
    <input type="submit" value='Delete'>
  </form>
  <a href="{% url 'movies:index' %}">BACK</a>
  <hr>
  <h5>댓글 목록</h5>
  <ul>
    {% for comment in comments  %}
      <li>{{ comment.content }}</li>
      <!--delete-->
      {% if request.user == comment.user %}
        <form action="{% url 'movies:comments_delete' movie.pk comment.pk %}" method='POST'>
          {% csrf_token %}
          <input type="submit" value="Delete">
        </form>
      {% else %}
        <p>다른 유저가 작성한 댓글</p>
      {% endif %}
    {% endfor %}
  </ul>
  <hr>
  <!--댓글 작성-->
  <form action="{% url 'movies:comments_create' movie.pk %}" method='POST'>
    {% csrf_token %}
    {{comment_form}}
    <input type="submit" value="제출">
  </form>
{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'movies:create' %}">[CREATE]</a>
  <hr>
  {% for movie in movies %}
    <a href="{% url 'movies:detail' movie.pk %}"><p>{{ movie.title }}</p></a>
    <!--좋아요 버튼-->
    <form action="{% url 'movies:likes' movie.pk %}" method='POST'>
      {% csrf_token %}
      {% if request.user in movie.like_users.all %}  
        <input type="submit" value="좋아요 취소">  <!--좋아요가 되어 있으면 좋아요 취소-->
      {% else %}
        <input type="submit" value="좋아요">
      {% endif %}
    </form>
    {% comment %} follow {% endcomment %}
    Follow하기: <a href="{% url 'accounts:follow' movie.user.username %}">{{movie.user}}</a>
    <hr>
  {% endfor %}
{% endblock %}

movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <hr>
  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">TITLE</label>
      <input type="text" id="title" name="title" value="{{ movie.title }}">
    </div>
    <div>
      <label for="description">DESCRIPTION</label>
      <textarea id="description" rows="3" name="description">{{ movie.description }}</textarea>
    </div>
    <input type="reset" value="Reset">
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:detail' movie.pk %}">BACK</a>
{% endblock %}