accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/', views.follow, name='follow'),

]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    # ===================== 댓글 =======================
    path('movies/<int:pk>/comments/', views.comments_create, name='comments_create'),  # 단일 댓글 데이터 저장
    path('movies/<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),  # 단일 댓글 데이터 삭제
    path('movies/<int:movie_pk>/likes/', views.likes, name='likes'),  # 단일 영화 데이터 좋아요 및 좋아요 취소
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

# custom user class
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'password', )

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.views.decorators.http import require_safe, require_POST, require_http_methods

from .forms import CustomUserChangeForm, CustomUserCreationForm
from .models import User

# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)
        
@require_POST
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/change_password.html', context)

@require_safe
def profile(request, username):
    person = get_user_model().objects.get(username=username)
    followings = person.followings.all()
    followers = person.followers.all()
    movies = person.like_movies.all()
    context = {
        'person': person,
        'followings': followings,
        'followers': followers,
        'movies': movies,
    }
    return render(request, 'accounts/profile.html', context)


def follow(request, username):
    user_to_follow = get_user_model().objects.get(username=username)
    print(user_to_follow)
    user = request.user
    print(user)
    if user != user_to_follow:
        if user_to_follow in user.followings.all():
            user.followings.remove(user_to_follow)
        else:
            user.followings.add(user_to_follow)
    return redirect('accounts:profile', user_to_follow.username)
    

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url 'accounts:change_password' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">
</form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ person.username }}'s Profile</h1>
<hr>

{% comment %} print follow/following {% endcomment %}
<h4>Follows: {{ followings|length }}</h4>
<ul>
	{% for following in followings %}
		<li>
			{{ following }}
		</li>
	{% endfor %}
</ul>
<hr>

{% comment %} show cnt of Followers & All Followers{% endcomment %}
<h4>Followers: {{ followers|length }}</h4>
<ul>
	{% for follower in followers %}
		<li>
			{{ follower }}
		</li>
	{% endfor %}
</ul>
<hr>

{% comment %} show cnt of Followings & All Followings{% endcomment %}
<h4>Likes these movies:</h4>
<ul>
	{% for movie in movies %}
	<li>
		{{ movie }}
	</li>
	{% endfor %}
</ul>
<hr>

<a href="{% url 'movies:index' %}">to main page</a>
<hr>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>Signup</h1>
<form action="{% url 'accounts:signup' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">
</form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
<h1>회원정보수정</h1>
<form action="{% url 'accounts:update' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">
</form>
{% endblock content %}